### **Import necessary libraries**

In [29]:
import os
import sys
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

notebook_dir = os.getcwd()
parent_dir = os.path.abspath(os.path.join(notebook_dir, '..'))
data_dir = os.path.join(parent_dir, 'data')
sys.path.append(parent_dir)

from utils.helper import *

### **Load the dataset**

In [30]:
%%capture
from datasets import load_dataset

dataset = load_dataset("ncduy/mt-en-vi")

In [31]:
dataset

DatasetDict({
    train: Dataset({
        features: ['en', 'vi', 'source'],
        num_rows: 2884451
    })
    validation: Dataset({
        features: ['en', 'vi', 'source'],
        num_rows: 11316
    })
    test: Dataset({
        features: ['en', 'vi', 'source'],
        num_rows: 11225
    })
})

In [32]:
train = dataset['train'].to_pandas()
val = dataset['validation'].to_pandas()
test = dataset['test'].to_pandas()

In [33]:
envi_data = pd.concat(
    [
        train, 
        val,
        test
    ]
)
envi_data.reset_index(drop=True, inplace=True)

In [34]:
envi_data.head()

,en,vi,source
0,"- Sorry, that question's not on here.","- Xin lỗi, nhưng mà ở đây không có câu hỏi đấy.",OpenSubtitles v2018
1,He wants you to come with him immediately.,Ông ấy muốn bố đi với ông ấy ngay lập tức,OpenSubtitles v2018
2,I thought we could use some company.,Tôi nghĩ chúng ta có thể muốn vài người bạn đồ...,OpenSubtitles v2018
3,It was founded in 2008 by this anonymous progr...,Nó được sáng lập vào năm 2008 bởi một lập trìn...,TED2020 v1
4,"With both of these methods, no two prints are ...","Với cả hai phương pháp, không có hai bản in nà...",TED2020 v1

In [35]:
envi_data.tail()

,en,vi,source
2906987,It's important.,Đây là điều quan trọng.,TED2020 v1
2906988,I looked at him and I saw myself.,"Mình nhìn vào nó, và nhìn thấy chính con người...",OpenSubtitles v2018
2906989,In India it is distributed mainly on the plain...,"Tại Ấn Độ, nó phân bố chủ yếu trên các vùng đồ...",WikiMatrix v1
2906990,He moved to MIO Biwako Shiga in 2015.,Anh chuyển đến MIO Biwako Shiga năm 2015.,WikiMatrix v1
2906991,The words genius and musical are used in the s...,Những từ ngữ như thiên tài âm nhạc đã được sử ...,wikimedia v20210402

In [36]:
envi_data.shape

(2906992, 3)

### **Preprocess dataset**

In [37]:
from tqdm import tqdm

tqdm.pandas()

envi_data["en"] = envi_data["en"].progress_apply(
    lambda x: english_sentence_processing(x, max_length=50, filtering=True)
    # lambda x: english_sentence_processing(x, filtering=False)
)
print("Complete process English sentences")

envi_data["vi"] = envi_data["vi"].progress_apply(
    lambda x: vietnamese_sentence_processing(x, max_length=50, filtering=True)
    # lambda x: vietnamese_sentence_processing(x, filtering=False)
)
print("Complete process Vietnamese sentences")

  0%|          | 0/2906992 [00:00<?, ?it/s]e:\english-vietnamese-machine-translation\utils\helper.py:103: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  sentence = BeautifulSoup(sentence, "html.parser").get_text(separator=" ")
100%|██████████| 2906992/2906992 [01:15<00:00, 38636.05it/s]

Complete process English sentences

100%|██████████| 2906992/2906992 [01:15<00:00, 38573.71it/s]

Complete process Vietnamese sentences

In [38]:
envi_data.shape

(2906992, 3)

In [39]:
envi_data = envi_data[['en', 'vi']]

In [40]:
envi_data = envi_data.dropna().reset_index(drop=True)
envi_data = envi_data[(envi_data['en'] != "") & (envi_data['vi'] != "")].reset_index(drop=True)

In [41]:
envi_data.shape

(2702160, 2)

In [ ]:
envi_data.to_csv(os.path.join(data_dir, 'filtered_cleaned_dataset.csv'), index=False)
# envi_data.to_csv(os.path.join(data_dir, 'cleaned_dataset.csv'), index=False)