### **Import necessary libraries**

In [ ]:
import nltk
import spacy 
import pandas as pd 
import numpy as np

In [2]:
from datasets import load_dataset

dataset = load_dataset("tdtunlp/open_subtitles_envi")
dataset

C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

DatasetDict({
    train: Dataset({
        features: ['en', 'vi'],
        num_rows: 3505276
    })
})

In [3]:
mydata = dataset['train'].to_pandas()
mydata.head(10)

,en,vi
0,"Previously on ""The Blacklist""...",Trong phần trước của phim
1,- You want to call your daddy?,- Cháu muốn gọi cho bố hả?
2,"- Yeah, I want to tell him I'm okay.","- Vâng, cháu muốn nói với bố là cháu vẫn ổn."
3,Okay.,Được rồi.
4,Lizzy...,Lizzy...
5,Be careful of your husband.,Hãy cẩn thận với chồng cô.
6,I can only lead you to the truth.,Tôi chỉ có thể dẫn dắt cô tìm ra sự thật
7,I can't make you believe it.,Tôi không thể khiến cô tin điều đó.
8,She's calling herself Jolene Parker.,Cô ta tự gọi cho mình Jolene Parker.
9,"Elizabeth Keen is not your wife, she's your ta...","Elizabeth Keen không phải vợ anh, cô ta là mục..."

In [4]:
mydata.tail(10)

,en,vi
3505266,"Boxing is about kids like me, who, wherever th...","Boxing với những người như tôi, dù đến từ đâu,..."
3505267,"Whether it's direction, or discipline, or glor...","Dù là định hướng, hay kỷ luật, hay vinh quang,..."
3505268,"A champion is someone who, despite tremendous ...","Nhà vô địch là người bất chấp những khó khăn, ..."
3505269,These dreams are still born every day in gyms ...,Những ước mơ này mỗi ngày vẫn nảy sinh ở các p...
3505270,And as long as there are kids who need to figh...,Và khi vẫn còn những đứa trẻ cần chiến đấu để ...
3505271,"Hey, hey, hey! The strategy remains the same, ...","Chiến lược vẫn thế, quy tắc cơ bản nhất của võ..."
3505272,"And still undefeated, Chris ""Lil B-Hop"" Colbert!","Và vẫn là Chris ""Lil B-Hop"" Colbert bất bại!"
3505273,Let's go! Let's go!,Đi nào!
3505274,Who's that?,Ai thế?
3505275,Who is that?,"10 THÁNG SAU TRẬN THUA ĐẦU TIÊN, PETER VẪN CHƯ..."

In [5]:
mydata.duplicated().sum()

np.int64(449663)

### **Drop the missing values and remove duplicates**

In [6]:
mydata.dropna(inplace=True)
mydata.drop_duplicates(inplace=True)
mydata.reset_index(drop=True, inplace=True)

In [7]:
mydata.shape

(3055613, 2)

### **Clean data**

In [ ]:
import re


def clean_data(sentence: str) -> str:
    # strip extra white space
    sentence = sentence.strip()

    # convert text to lower case
    sentence = sentence.lower()

    # Remove extra whitespace within sentences
    sentence = re.sub(r"\s+", " ", sentence)

    return sentence

In [9]:
mydata = mydata.map(clean_data)

In [ ]:
import spacy
from spacy.symbols import ORTH

nlp = spacy.load("en_core_web_sm")
nlp.tokenizer.add_special_case("...", [{ORTH: "..."}])


def tokenize_and_join(sentence: str) -> list:
    doc = nlp(sentence)
    return " ".join([token.text for token in doc])

In [ ]:
# # cnt = 0
# # cnt = 1000001
# cnt = 2000001

# # while cnt <= 1000000:
# # while cnt <= 2000000:
# while cnt <= 3000000:
#     mydata.iloc[cnt, :] = mydata.iloc[cnt, :].map(tokenize_and_join)
#     if cnt % 100 == 0:
#         print(cnt)
#     cnt += 1

# print("Complete map the tokenize_and_join function")

In [12]:
# # part1 = mydata.iloc[:1000001]
# # part2 = mydata.iloc[1000001:2000001]
# part3 = mydata.iloc[2000001:3000001]

# # print("Complete load part1 !!!!")
# # print("Complete load part2 !!!!")
# print("Complete load part3 !!!!")

In [ ]:
# # envi_dataset = part1.to_csv('envi_dataset_part1.csv', index=False)
# # envi_dataset = part2.to_csv('envi_dataset_part2.csv', index=False)
# envi_dataset = part3.to_csv('envi_dataset_part3.csv', index=False)

In [14]:
# print("Load to CSV completed !!!")

In [ ]:
envi_data = pd.concat(
    [
        pd.read_csv("envi_dataset_part1.csv"),
        pd.read_csv("envi_dataset_part2.csv"),
        pd.read_csv("envi_dataset_part3.csv"),
    ]
)
envi_data.shape

(3000001, 2)

In [22]:
envi_data.head(10)

,en,vi
0,"previously on "" the blacklist "" ...",trong phần trước của phim
1,- you want to call your daddy ?,- cháu muốn gọi cho bố hả ?
2,"- yeah , i want to tell him i 'm okay .","- vâng , cháu muốn nói với bố là cháu vẫn ổn ."
3,okay .,được rồi .
4,lizzy ...,lizzy ...
5,be careful of your husband .,hãy cẩn thận với chồng cô .
6,i can only lead you to the truth .,tôi chỉ có thể dẫn dắt cô tìm ra sự thật
7,i ca n't make you believe it .,tôi không thể khiến cô tin điều đó .
8,she 's calling herself jolene parker .,cô ta tự gọi cho mình jolene parker .
9,"elizabeth keen is not your wife , she 's your ...","elizabeth keen không phải vợ anh , cô ta là mụ..."

In [21]:
envi_data.to_csv('envi_dataset.csv', index=False)